// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/health/controllers/get_health_controller.ts').default['execute'], false>
}
type PricingGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/prices/controllers/get_pricing_controller.ts').default['validators']>>
  response: MakeTuyauResponse<import('../app/prices/controllers/get_pricing_controller.ts').default['execute'], true>
}
export interface ApiDefinition {
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'pricing': {
    '$url': {
    };
    '$get': PricingGetHead;
    '$head': PricingGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'health',
    path: '/health',
    method: ["GET","HEAD"],
    types: {} as HealthGetHead,
  },
  {
    params: [],
    name: 'pricing',
    path: '/pricing',
    method: ["GET","HEAD"],
    types: {} as PricingGetHead,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
